# Generated by Django 3.0.14 on 2024-09-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
